### ISSUE TITLE
Does not work when installed via hex

### ISSUE THREAD

**Issue by scouten** [tallakt/stream_split#1]
After installing stream_split, I am unable to run tests in my application due to the following:

```
 mix deps.compile stream_split
==> stream_split
could not compile dependency :stream_split, "mix compile" failed. You can recompile this dependency with "mix deps.compile stream_split", update it with "mix deps.update stream_split" or clean it with "mix deps.clean stream_split"
```

None of the remedies suggested by `mix` help. This is small enough and I'm using it in a corner of my own test suite, so it's not a blocker. I'll just copy the code in directly. But a fix might help the next user of stream_split.

**Comment by tallakt** [comment]
Sorry about that. Fixed in 0.1.1

Thanks for reporting
